parameters:
    penngroups:
        username:       "%penngroups.username%"
        password_file:  "%penngroups.credential%"
        cache_timeout:  600

services:
    ## Dependency for reading passwords
    storage.encrypted:
        class:  SAS\IRAD\FileStorageBundle\Service\EncryptedFileStorageService
        arguments:  [ "%penngroups.file_storage%" ]

    ## service for penngroups queries
    penngroups.ldap_query:
        class: SAS\IRAD\PennGroupsBundle\Service\LDAPQuery
        arguments:  [ @storage.encrypted, "%penngroups%" ]

    penngroups.web_service_query:
        class: SAS\IRAD\PennGroupsBundle\Service\WebServiceQuery
        arguments:  [ @storage.encrypted, "%penngroups%" ]

    penngroups.query_cache: 
        class: SAS\IRAD\PennGroupsBundle\Service\PennGroupsQueryCache
        arguments: [ @session, @penngroups.web_service_query, "%penngroups%" ]
