services:

    ## service for penngroups queries
    penngroups.ldap_query:
        class: SAS\IRAD\PennGroupsBundle\Service\LDAPQuery
        arguments:  [ "%penngroups%" ]

    penngroups.web_service_query:
        class: SAS\IRAD\PennGroupsBundle\Service\WebServiceQuery
        arguments:  [ "%penngroups%" ]
        
    penngroups.query_cache: 
        class: SAS\IRAD\PennGroupsBundle\Service\PennGroupsQueryCache
        arguments: [ "%penngroups%", @session, @penngroups.web_service_query ]